### ISSUE TITLE
Select a dev stack

### ISSUE THREAD

**Issue by D3Portillo** [nodeschoolsm/website#1]
Hola, seleccionemos una Stack de desarrollo para el sitio

**Comment by Monge1h** [comment]
> Hola, seleccionemos una Stack de desarrollo para el sitio

Considero que para sacar un mvp lo mas rápido posible sea un stack que ya manejemos o con el cual nos sintamos mas cómodos.

**Comment by D3Portillo** [comment]
Me parece, 
Listare con las que puedo trabajar,
React, vue, mongodb, nodejs, gatsby, nuxt , nextjs y express,

para hosting, puede ser netlify, zeit.co, o aws ?

**Comment by D3Portillo** [comment]
@SoldierHD , :)

**Comment by Monge1h** [comment]
Yo puedo trabajar en el backend con nodejs/express y db mysql y mongodb; pero antes de seleccionar el stack creo que deberiamos delimitar que es lo que se quiere hacer, o el alcance del proyecto, para asi elegir el stack que convenga mas.

**Comment by D3Portillo** [comment]
Chivísimo, me parece, 
# IDEAS QUE PUEDE TENER EL SITO
- tiendita de swagg
- registro de usuarios
- landing de explicación general de NSSM
- apartado para ponentes
- hosteo de los certificados
- blog

**Comment by Monge1h** [comment]
> # IDEAS QUE PUEDE TENER EL SITO
Considero que esto de las ideas y funcionalidades puede estar en otra issue, continuar con las ideas en #2

**Comment by h12guerrero** [comment]
Estoy de acuerdo con lo que dice Monge. 
Y lo otro si se elige un stack con nodejs por mi no hay problema solo que aprendería con uds xD

**Comment by D3Portillo** [comment]
> Estoy de acuerdo con lo que dice Monge.
> Y lo otro si se elige un stack con nodejs por mi no hay problema solo que aprendería con uds xD

>No problema :raised_hands: , que tecnologías de backend y frontend manejas @SoldierHD  ?

Manejo más tecnologías con php (frameworks), js & Python para el back y front no lo manejo mucho pero igual js, y poco de react and vue

**Comment by D3Portillo** [comment]
Para ver si se usa JAM Stack, y dejar seccionada la plataforma en API's

**Comment by Monge1h** [comment]
A mi me gustaría aprender a usar nest js, para backend ,no se que opinan al respecto.

**Comment by D3Portillo** [comment]
> A mi me gustaría aprender a usar nest js, para backend ,no se que opinan al respecto.

Usariamos SSR , para hosting, serverless ?

**Comment by Monge1h** [comment]
Nunca he trabajado con SSR, en cuanto al hosting creo que lo ideal seria usar serverless, es mas economico.

**Comment by D3Portillo** [comment]
> Nunca he trabajado con SSR, en cuanto al hosting creo que lo ideal seria usar serverless, es mas economico.


Si no usaremos SSR, puede quedarse algo estatíco con Nuxt o Gatsby, lo de serverless me parece, pero no solo por que sea más barato :)

**Comment by D3Portillo** [comment]
### Propuesta stack (luego de evaluar la magnitud del sitio)[Usando JAM]
#### Frontend
- Reactjs
- Gatsby
- Tailwindcss

#### Backend
- NestJs ?
- MongoDB
- AWS Lambda y API Gateway
----
- Para archivos estatícos podemos usar S3 de AWS
- Podemos usar un cluster de Atlas para texto (creo que aguanta, si no lo movemos a una instancia o vm)

**Comment by D3Portillo** [comment]
>@Monge1h , @SoldierHD , que piensan de este stack?

Por mi está bien y let’s get it rock xD 

O que opinas @Monge1h?

**Comment by Monge1h** [comment]
Yo estoy probando lo de NestJs a serverless para ver que tan factible es

> * Podemos usar un cluster de Atlas para texto (creo que aguanta, si no lo movemos a una instancia o vm)

^^
Puedes explicar un poco mas de esto?

**Comment by D3Portillo** [comment]
> Yo estoy probando lo de NestJs a serverless para ver que tan factible es
> 
> > * Podemos usar un cluster de Atlas para texto (creo que aguanta, si no lo movemos a una instancia o vm)
> 
> ^^
> Puedes explicar un poco mas de esto?

Si necesitamos una db, con información, mails, hash o indentificador de reconocimiento, y para archivos pesados(los pdf de los reconocimientos), se hostean en un bucket

**Comment by D3Portillo** [comment]
> Yo estoy probando lo de NestJs a serverless para ver que tan factible es
> 
> > * Podemos usar un cluster de Atlas para texto (creo que aguanta, si no lo movemos a una instancia o vm)
> 
> ^^
> Puedes explicar un poco mas de esto?

Usando mongodb atlas, si pasamos del free-tier, luego la movemos, pero por el momento, la soca el free tier
