### ISSUE TITLE
IDEAS DE FUNCIONALIDADES PARA EL SITIO

### ISSUE THREAD

**Issue by Monge1h** [nodeschoolsm/website#2]
# IDEAS QUE PUEDE TENER EL SITO
- tiendita de swagg
- registro de usuarios
- landing de explicación general de NSSM
- apartado para ponentes
- hosteo de los certificados
- blog

_Originally posted by @D3Portillo in https://github.com/Nodeshool-San-Miguel/website/issues/1#issuecomment-544189276_

**Comment by Monge1h** [comment]
- Cuando se acerque la fecha de un evento enviar correos a los usuarios para recordarles que se registren.

**Comment by D3Portillo** [comment]
Dejar un usuario super admin que tenga una dashboard para calendarización

**Comment by D3Portillo** [comment]
> Dejar un usuario super admin que tenga una dashboard para calendarización

Minimá, con opciones, de agregar a calendario, enviar mails, etc

**Comment by D3Portillo** [comment]
>     * Cuando se acerque la fecha de un evento enviar correos a los usuarios para recordarles que se registren.

Meetup?

**Comment by Monge1h** [comment]
> Meetup?

Por el momento creo que sí, es lo más rápido, ya luego se puede pensar en otras alternativas.

**Comment by Monge1h** [comment]
> * apartado para ponentes

Que conlleva este apartado?
Podrán subir sus diapositivas?

**Comment by D3Portillo** [comment]
> > * apartado para ponentes
> 
> Que conlleva este apartado?
> Podrán subir sus diapositivas?

Exacto, subir sus diapos, recursos, linkear URL's, y opciones de visualizar, compartir y descargar su reconocimiento

**Comment by Monge1h** [comment]
# Recapitulación: 

- tiendita de swagg
- registro de usuarios
- landing de explicación general de NSSM
- apartado para ponentes
- hosteo de los certificados
- blog
- Dejar un usuario super admin que tenga una dashboard para calendarización con opciones, de agregar a calendario, enviar mails, etc
- Cuando se acerque la fecha de un evento enviar correos a los usuarios para recordarles que se registren.

**Comment by Monge1h** [comment]
Cual seria la prioridad?

**Comment by D3Portillo** [comment]
Podemos seccionar en un Project , cáda apartado, y empezar por lo más importante
1. Landing de explicación general de NSSM
2. Hosteo de los certificados
3. Dejar un usuario super admin que tenga una dashboard para calendarización con opciones, de agregar a calendario, enviar mails, etc
4. Cuando se acerque la fecha de un evento enviar correos a los usuarios para recordarles que se registren.
5. Apartado[dashboard] para ponentes
6. Blog
7. Tienda de Swag
